### ISSUE TITLE
can you explain the output of the program a little bit ,such as the output.txt, i get this and i don't know what  does it means

### ISSUE THREAD

**Issue by Oliver-0423** [abraunst/decycler#1]
20 6 72 6 97 39
19 10 74 10 95 42
18 11 11 11 94 44
17 15 2 15 92 48
16 18 69 18 91 51
15 20 16 20 90 56
14 28 67 28 88 61
13 31 14 31 86 64
12 60 3 60 85 70
11 61 13 61 85 74
10 62 22 62 85 81
9 63 30 63 85 88
8 64 35 64 85 93
7 65 40 65 85 98
6 66 48 66 85 101
5 67 56 67 85 104
4 68 63 68 85 109
3 69 70 69 85 113
2 71 37 71 84 122
1 73 66 73 83 127
S 31

**Comment by abraunst** [comment]
This comes from `reverse_greedy.cpp` line 216:
```c++
cout << t << " " << ngiant << " " << ibest << " " << nbest << " " << num_comp << " " << nedges <<  endl;
```

t: number of remaining seeds (i.e. removed vertices) 
ngiant: size of the largest component
ibest: reinserted seed
nbest: size of the component of that seed
num_comp: number of components
nedges: number of edges

**Comment by abraunst** [comment]
In practice, you can ignore those lines and just consider the lines starting with S

**Comment by Oliver-0423** [comment]
thanks,this helped me a lot
